---
openapi: 3.0.0
info:
  title: NoteBook
  description: Лабораторна робота №5 Варіант-2
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/fayon/Laba_5/1.0.0
  description: Laba_5
tags:
- name: user
paths:
  /notes:
    get:
      tags:
      - user
      summary: Список всіх заміток
      responses:
        "200":
          description: вивело всі замітки
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
        "400":
          description: Проблема
    post:
      tags:
      - user
      summary: Додати замітку
      operationId: addNote
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
        required: true
      responses:
        "201":
          description: Замітка додана
          links:
            address:
              operationRef: https://virtserver.swaggerhub.com/fayon/Laba_5/1.0.0/notes
        "400":
          description: Непавильний інпут
  /notes/{id}:
    get:
      tags:
      - user
      summary: Замітка під певним ід
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: вивело замітку
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        "400":
          description: Проблема
  /notes/{id}/edit:
    put:
      tags:
      - user
      summary: Редагувати замітку
      operationId: editNote
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
        required: true
      responses:
        "201":
          description: Замітка редагована
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserStat'
          links:
            address:
              operationRef: https://virtserver.swaggerhub.com/fayon/Laba_5/1.0.0/notes
        "400":
          description: Неправильний інпут
        "403":
          description: перевищена кількість редагувань
          links:
            address:
              operationRef: https://virtserver.swaggerhub.com/fayon/Laba_5/1.0.0/notes
  /notes/{id}/delete:
    delete:
      tags:
      - user
      summary: Видалити замітку
      operationId: deleteNote
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "201":
          description: Замітка видалена
          links:
            address:
              operationRef: https://virtserver.swaggerhub.com/fayon/Laba_5/1.0.0/notes
        "400":
          description: Помилка
        "403":
          description: Замітку не найдено
          links:
            address:
              operationRef: https://virtserver.swaggerhub.com/fayon/Laba_5/1.0.0/notes
  /userstats/{id}:
    get:
      tags:
      - user
      summary: Конкретний юзер
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Вивело юзера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserStat'
        "400":
          description: Проблема
components:
  schemas:
    Note:
      required:
      - numberEdits
      - tag
      - text
      type: object
      properties:
        text:
          maxLength: 404
          type: string
        tag:
          type: string
        numberEdits:
          maximum: 5
          minimum: 0
          type: integer
    UserStat:
      required:
      - countNotes
      - id
      - statistic
      - user_name
      type: object
      properties:
        user_name:
          type: string
        id:
          type: integer
          format: uuid
        countMessages:
          type: integer
        statistic:
          type: array
          items:
            required:
            - timeEdited
            - userWhoEdit
            type: object
